USE [master]
GO
/****** Object:  Database [qa_search]    Script Date: 20.06.2019 16:58:55 ******/
CREATE DATABASE [qa_search]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'qa_search', FILENAME = N'E:\MSSQL\DATA\qa_search.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'qa_search_log', FILENAME = N'E:\MSSQL\LOG\qa_search_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [qa_search].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [qa_search] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [qa_search] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [qa_search] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [qa_search] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [qa_search] SET ARITHABORT OFF 
GO
ALTER DATABASE [qa_search] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [qa_search] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [qa_search] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [qa_search] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [qa_search] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [qa_search] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [qa_search] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [qa_search] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [qa_search] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [qa_search] SET  DISABLE_BROKER 
GO
ALTER DATABASE [qa_search] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [qa_search] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [qa_search] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [qa_search] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [qa_search] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [qa_search] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [qa_search] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [qa_search] SET RECOVERY FULL 
GO
ALTER DATABASE [qa_search] SET  MULTI_USER 
GO
ALTER DATABASE [qa_search] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [qa_search] SET DB_CHAINING OFF 
GO
ALTER DATABASE [qa_search] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [qa_search] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [qa_search] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'qa_search', N'ON'
GO
ALTER DATABASE [qa_search] SET QUERY_STORE = OFF
GO
USE [qa_search]
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
ALTER DATABASE [qa_search] SET  READ_WRITE 
GO
